#include <check.h>
#include <stdio.h>
#include <socket_factory.h>
#include <stdbool.h>

START_TEST(default_test)
{
    socket_factory_t * factory = tcp_server_setup(
        "5000", NULL,
        512,
        false);

    ck_assert_ptr_ne(factory, NULL);

    // Struct that stores client address information generated by accept()
    struct sockaddr clientAddress;
    socklen_t clientAddressLength = sizeof(clientAddress);

    printf("Connect to me with: \necho -n 'f103' | nc -q2 localhost "
           "5000\n");
    int client_socket = accept(
        factory->socket,
        &clientAddress,
        &clientAddressLength
        );

    if (client_socket < 0)
    {
        perror("Failed to accept client socket.");
        exit(EXIT_FAILURE);
    }
    printf("Accepted!\n");


    factory_destroy(factory);

}END_TEST


static TFun creation_default_test[] = {
    default_test,
    NULL
};


static void add_tests(TCase * test_cases, TFun * test_functions)
{
    while (* test_functions) {
        // add the test from the core_tests array to the t-case
        tcase_add_test(test_cases, * test_functions);
        test_functions++;
    }
}

Suite * socket_factory_test_suite(void)
{
    // suite creation
    Suite * suite = suite_create("\n Socket Factory Tester");
    TFun * test_list;
    TCase * test_cases;

	// add tests to suite
    test_list = creation_default_test;
    test_cases = tcase_create(" Socket Factory Testing");
    add_tests(test_cases, test_list);

     //use this to control timesouts when using sleeps
     tcase_set_timeout(test_cases, 0);

    suite_add_tcase(suite, test_cases);


    return suite;
}

/*** end of file ***/

